id: 524c65492d5f4de98d69f91a28031b40
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_679-Dharan%C4%AB_Praising_the_Qualities_of_the_Immeasurable_One-v2
  language: bo
  author: ''
  volume: {}
